# Generated by Django 5.2.5 on 2025-09-21 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_app', '0001_initial'),
        ('teachers', '0002_teacher_address_teacher_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classsubjectassignment',
            options={'ordering': ['class_program', 'subject']},
        ),
        migrations.AlterField(
            model_name='classprogram',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classes', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='classsubjectassignment',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_assignments', to='teachers.teacher'),
        ),
    ]
