# Generated by Django 5.2.5 on 2025-09-21 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_app', '0002_alter_classsubjectassignment_options_and_more'),
        ('schools', '0001_initial'),
        ('teachers', '0002_teacher_address_teacher_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classprogram',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optional_classes', to='teachers.teacher'),
        ),
        migrations.CreateModel(
            name='ClassTeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_homeroom_teacher', models.BooleanField(default=False)),
                ('class_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='classes_app.classprogram')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='schools.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='teachers.teacher')),
            ],
            options={
                'ordering': ['class_program', 'teacher'],
                'unique_together': {('class_program', 'teacher')},
            },
        ),
        migrations.AddField(
            model_name='classprogram',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='classes', through='classes_app.ClassTeacherAssignment', to='teachers.teacher'),
        ),
    ]
