# Generated by Django 5.2.5 on 2025-09-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_app', '0003_alter_classprogram_teacher_classteacherassignment_and_more'),
        ('teachers', '0006_alter_teacher_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classprogram',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='assigned_classes', through='classes_app.ClassTeacherAssignment', to='teachers.teacher'),
        ),
    ]
