# Generated by Django 5.2.5 on 2025-09-24 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_app', '0004_alter_classprogram_teachers'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E.g., Period 1, Math, or 08:00 - 08:45', max_length=100)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('class_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='classes_app.classprogram')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='schools.school')),
            ],
            options={
                'ordering': ['class_program', 'start_time'],
                'unique_together': {('class_program', 'name')},
            },
        ),
    ]
