# Generated by Django 5.2.5 on 2025-08-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='billing_cycle',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half-Yearly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom')], default='MONTHLY', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='custom_months',
            field=models.PositiveIntegerField(blank=True, help_text='If CUSTOM is selected, enter number of months', null=True),
        ),
    ]
