# Generated by Django 5.2.5 on 2025-08-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_alter_invoice_options_alter_invoice_fee_and_more'),
        ('students', '0002_student_billing_cycle_student_custom_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fee_structures',
            field=models.ManyToManyField(blank=True, help_text='Select one or more fee structures for this student', to='fees.feestructure'),
        ),
    ]
