# Generated by Django 5.2.5 on 2025-08-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_fee_structures'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Outstanding balance before joining the system', max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='starting_billing_month',
            field=models.DateField(blank=True, help_text='Month from which this system should start billing this student', null=True),
        ),
    ]
