# Generated by Django 5.2.5 on 2025-09-30 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_date_of_birth_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(help_text='Enter phone as 09XXXXXXXX', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format 09XXXXXXXX (10 digits, starts with 09).', regex='^09\\d{8}$')]),
        ),
    ]
