version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_volume:/app/media
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-dev-key-change-in-production
    depends_on:
      - db

  npm:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: npm run watch
    
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: schoolsystem
      POSTGRES_USER: schoolsystem
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  media_volume: