# Generated by Django 5.2.5 on 2025-08-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='name',
            field=models.CharField(choices=[('TUITION', 'Tuition'), ('REGISTRATION   ', 'Registration'), ('TRANSPORT', 'Transport'), ('OTHER', 'Other')], default='TUITION', max_length=20),
        ),
    ]
