# Generated by Django 5.2.5 on 2025-08-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_alter_feestructure_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='name',
            field=models.CharField(choices=[('TUITION', 'Tuition'), ('REGISTRATION   ', 'Registration'), ('OTHER', 'Other')], default='TUITION', max_length=20),
        ),
    ]
