# Generated by Django 5.2.5 on 2025-08-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_alter_feestructure_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, help_text='Optional: Bank transfer ID, MPesa code, or Stripe transaction ID', max_length=100, null=True),
        ),
    ]
