# Generated by Django 5.2.5 on 2025-08-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billing_month',
            field=models.DateField(blank=True, help_text='The month this invoice is for', null=True),
        ),
    ]
