# Generated by Django 5.2.5 on 2025-08-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_alter_invoice_options_alter_invoice_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
