# Generated by Django 5.2.5 on 2025-08-29 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_invoice_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='fees.feestructure'),
        ),
    ]
