# Generated by Django 5.2.5 on 2025-08-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0008_alter_invoice_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='name',
            field=models.CharField(choices=[('TUITION', 'Tuition'), ('TRANSPORT', 'Transport'), ('REGISTRATION', 'Registration'), ('OTHER', 'Other')], default='TUITION', max_length=20),
        ),
    ]
