# Generated by Django 5.2.5 on 2025-09-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0009_alter_feestructure_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, help_text='Optional: Bank transfer ID, MPesa code, or Tele Birr transaction ID', max_length=100, null=True),
        ),
    ]
