# Generated by Django 5.2.5 on 2025-09-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0010_alter_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_type',
            field=models.CharField(choices=[('single', 'Single receipt for all invoices'), ('separate', 'Separate receipt for each invoice'), ('none', 'No receipt')], default='single', max_length=20),
        ),
    ]
