# Generated by Django 5.2.5 on 2025-09-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0011_payment_receipt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
