# Generated by Django 5.2.5 on 2025-10-05 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0013_rename_is_finalized_payment_is_reversed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mobile_provider',
            field=models.CharField(blank=True, help_text='If Mobile Money, specify provider', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_file',
            field=models.FileField(blank=True, help_text='Upload bank transfer receipt if applicable', null=True, upload_to='payment_receipts/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Mobile Money', 'Mobile Money (M-Pesa, Tele Birr, etc.)'), ('Bank Transfer', 'Bank Transfer'), ('Online', 'Online Payment')], default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(blank=True, help_text='Who received the payment (accountant or parent user)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, help_text='Required for Mobile Money and Bank Transfer payments: transaction ID', max_length=100, null=True),
        ),
    ]
