# Generated by Django 5.2.5 on 2025-10-05 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0015_remove_payment_mobile_provider_payment_confirmed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='fees_paymen_invoice_cdcf53_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='fees_paymen_externa_83e628_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='fees_paymen_paid_on_d9d278_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='fees_paymen_status_42ba84_idx',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='payment',
            name='confirmed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_confirmed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='external_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(default='Cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='payment_receipts/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_type',
            field=models.CharField(choices=[('single', 'Single receipt for all invoices'), ('separate', 'Separate receipt for each invoice'), ('none', 'No receipt')], default='single', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, help_text='Bank transfer ID, MPesa code, TeleBirr transaction ID, or internal ref', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNCONFIRMED', 'Unconfirmed'), ('CONFIRMED', 'Confirmed'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20),
        ),
    ]
