# Generated by Django 5.2.5 on 2025-10-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0016_remove_payment_fees_paymen_invoice_cdcf53_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNCONFIRMED', 'Unconfirmed'), ('CONFIRMED', 'Confirmed'), ('REVERSED', 'Reversed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
