# Generated by Django 5.2.5 on 2025-09-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super Admin"),
                    ("SCHOOL_ADMIN", "School Admin"),
                    ("TEACHER", "Teacher"),
                    ("PARENT", "Parent"),
                    ("ACCOUNTANT", "ACCOUNTANT"),
                ],
                default="PARENT",
                max_length=20,
            ),
        ),
    ]
