# Generated by Django 5.2.5 on 2025-09-21 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacher_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must start with 251 and be 11–12 digits long (e.g. 251960306801).', regex='^\\+251\\d{9}$')]),
        ),
    ]
