# Generated by Django 5.2.5 on 2025-10-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Stores the Telegram chat ID once user connects', max_length=64, null=True),
        ),
    ]
