# Generated by Django 5.2.5 on 2025-10-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_parentprofile_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentprofile',
            options={'verbose_name': 'Parent Profile', 'verbose_name_plural': 'Parent Profiles'},
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='parents/avatars/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Stores the unique Telegram chat ID once user connects.', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Telegram @username for reference (e.g., @yourname)', max_length=64, null=True),
        ),
    ]
