# Generated by Django 5.2.5 on 2025-09-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_announcement_options_announcement_classes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('ATTENDANCE', 'Attendance'), ('EVENT', 'Event'), ('ACADEMIC', 'Academic')], default='GENERAL', max_length=20),
        ),
    ]
