# Generated by Django 5.2.5 on 2025-09-26 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_app', '0005_session'),
        ('notifications', '0003_announcement_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Optional: restrict announcement to a specific division', null=True, on_delete=django.db.models.deletion.CASCADE, to='classes_app.division'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='target',
            field=models.CharField(choices=[('ALL', 'All Users'), ('TEACHERS', 'Teachers'), ('PARENTS', 'Parents'), ('CLASS', 'Specific Classes'), ('DIVISION', 'Specific Division')], default='ALL', max_length=20),
        ),
    ]
