# Generated by Django 5.2.5 on 2025-09-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_app', '0005_session'),
        ('notifications', '0004_announcement_division_alter_announcement_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='division',
        ),
        migrations.AddField(
            model_name='announcement',
            name='division',
            field=models.ManyToManyField(blank=True, help_text='Used when target=DIVISION', to='classes_app.division'),
        ),
    ]
