# Generated by Django 5.2.5 on 2025-09-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, max_length=15, null=True)),
                ('new_status', models.CharField(max_length=15)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', 'class_program', 'student']},
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='created_at',
            new_name='marked_at',
        ),
    ]
